### ISSUE TITLE
Custom ports not supported

### ISSUE THREAD

**Issue by bugbountyguy** [0perationPrivacy/VoIPSuite-Mobile#33]
Hi,

My local instance is not using port 443 for https due to the need to port forward via my VPN and the app on my server using the environment variable for internal redirects (so can't just setup my docker container to 54830:443 I think? I can try, but still think this should be looked into either way). When inputting my URL + a port number, the login screen says "Incorrect URL". I'm guessing `keyboardType="url"` doesn't support ports for some weird reason, or it's something else.

**Comment by 0perationPrivacy** [comment]
you can set port with the environment variabl `PORT` as mentioned in the [wiki](https://github.com/0perationPrivacy/voip/wiki/Cloud-Hosting#Environment-Variables)

The server will then run on that port. In your port forwarding rule in your firewall, you will forward traffic to that custom local IP/port.

If I'm not understanding you correct, DM me on Matrix.

**Comment by 0perationPrivacy** [comment]
@bugbountyguy I see your issue now. It's a simple fix. we're validating the URL right now with a regex that doesn't allow for port numbers at the end. I'll fix that to allow it. Stay tuned.
Thanks for discovering that.
I'll close it when it's fixed.

**Comment by huzaifa3115** [comment]
Closing this issue, this has been fixed in the latest release v-0.4
https://github.com/0perationPrivacy/VoIPSuite-Mobile/releases/tag/v-0.4
