### ISSUE TITLE
Lagged typing after text passes 6 lines

### ISSUE THREAD

**Issue by getsean** [0perationPrivacy/VoIPSuite-Mobile#38]
If you write a long text after about 6 lines the typing slows and lags and you can't correctly type anymore.

**Comment by getsean** [comment]
Also after you send it any additional texts will lag. You have to force close app and refresh to make it usable again

**Comment by huzaifa3115** [comment]
Hi,
this issue is already been highlighted by the tech team & has been fixed, will be available in the next release.

Thank you for the contribution
