### ISSUE TITLE
Add Tablet Support

### ISSUE THREAD

**Issue by ColoursofOSINT** [0perationPrivacy/VoIPSuite-Mobile#50]
Currently, although the website version more or less supports a tablet view (which is similar to the desktop view), the app only allows you to see the toolbar, current chats or the content of the chats. An option to view all three would be very nice.

**Comment by 0perationPrivacy** [comment]
I hear you, I tried to look at other similar apps to see how they design it, and this is similar to iMessage, WhatsApp Web, Signal and other messaging app interfaces.
If you can reference a UI/UX design with better functionality, I will be happy to look into it.

**Comment by ColoursofOSINT** [comment]
I was thinking three columns. 
First column is hidden with only icons, when one clicks on it it expands to the full sidebar (settings, contacts, etc).
Second and third columns are almost identical to the desktop view, where previews of the messages are shown and a full expanded view of the messages that you have selected.
